evo_strategy:
  default:
    lmda: 7
    mu: 30
    strategy: plus
    std: 0.1
  mu: [10, 20, 30]
  std: [0.1, 0.5, 1.0]
  strategy: ["comma", "plus"]

diff_evolution:
  default:
    f: 0.5
    crossover_rate: 0.5
  f: [0.0, 0.5, 1.0, 2.0]
  crossover_rate: [0.2, 0.5, 0.8]

symbiotic_optimisation:
  default:
    bf1: 1
    bf2: 2
  bf1: [1, 2]
  bf2: [1, 2]

simulated_annealing:
  default:
    std: 0.1
    temperature: 100
  temperature: [50, 100, 150]
  std: [0.01, 0.1, 0.2]

fractal_structurization:
  default:
    size: 50
    std: 0.5
    temperature: 10000
  size: [10, 20, 30]
  std: [0.01, 0.1, 0.2]
  temperature: [1000000, 100000, 10000]

deformed_stars:
  default:
    size: 50
    a: 3
    k: 4
    std: 0.1
  size: [10, 20, 30]
  a: [2, 3, 4]
  k: [3, 4, 5]
  std: [0.01, 0.1, 0.2]
